version: "2.2"

services:
  "android-container-v15":
    image:  docker.io/library/appium-v2:emulator_13.0_v2.1.3-p1
    container_name: android-container-v15
    privileged: true
    restart: always
    ports:
      - "6094:6080"
      - "4737:4723"
      - "5594:5594"
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S8
      - WEB_VNC=true
      - CONNECT_TO_GRID=false
      - RELAXED_SECURITY=true  
      - APPIUM=false
      - SELENIUM_HOST=192.168.0.37
      - SELENIUM_PORT=4244
      - AUTO_RECORD=false
      - MOBILE_WEB_TEST=false
      - APPIUM_HOST=192.168.2.173
      - NODE_PORT=5594
      - PUBLISH_PORT=4242
      - SUBSCRIBE_PORT=4243
      - SESSION_TIMEOUT=90
  "android-container-v16":
    image:  docker.io/library/appium-v2:emulator_13.0_v2.1.3-p1
    container_name: android-container-v16
    privileged: true
    restart: always
    ports:
      - "6095:6080"
      - "4738:4723"
      - "5596:5596"
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S8
      - WEB_VNC=true
      - CONNECT_TO_GRID=false
      - RELAXED_SECURITY=true  
      - APPIUM=false
      - SELENIUM_HOST=192.168.0.37
      - SELENIUM_PORT=4244
      - AUTO_RECORD=false
      - MOBILE_WEB_TEST=false
      - APPIUM_HOST=192.168.2.173
      - NODE_PORT=5596
      - PUBLISH_PORT=4242
      - SUBSCRIBE_PORT=4243
      - SESSION_TIMEOUT=90

